apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcertmanagerinstances.components.platform.pbsc
spec:
  group: components.platform.pbsc
  names:
    kind: XCertManagerInstance
    plural: xcertmanagerinstances
  claimNames:
    kind: CertManagerInstance
    plural: certmanagerinstances
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  namespace:
                    type: string
                required:
                  - namespace
            required:
              - parameters
